[package]
name = "memprint"
description = "A way to print memory layout of a struct"
version = "0.1.0"
edition = "2021"
license = "0BSD"

[dependencies]
colored = "2.1"
memprint_derive = { path = "memprint_derive", version = "0.1.0" }
